<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="L699DTRV" name="TestngFiles.LoginVerification" tests="9" failures="1" timestamp="18 Oct 2019 08:49:20 GMT" time="19.796" errors="0">
  <testcase name="LoginPage" time="0.009" classname="TestngFiles.LoginVerification"/>
  <testcase name="VerifyLogin" time="2.389" classname="TestngFiles.LoginVerification"/>
  <testcase name="VerifyMenu1" time="6.480" classname="TestngFiles.LoginVerification">
    <failure type="java.lang.AssertionError" message="expected [Employment Status] but found []">
      <![CDATA[java.lang.AssertionError: expected [Employment Status] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at TestngFiles.SubMenuVerification.AdminSubMenu2(SubMenuVerification.java:60)
at TestngFiles.HomePageValidation.Admin(HomePageValidation.java:45)
at TestngFiles.LoginVerification.VerifyMenu1(LoginVerification.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifyMenu1 -->
  <testcase name="VerifyMenu2" time="1.921" classname="TestngFiles.LoginVerification"/>
  <testcase name="VerifyMenu3" time="2.644" classname="TestngFiles.LoginVerification"/>
  <testcase name="VerifyMenu4" time="1.212" classname="TestngFiles.LoginVerification"/>
  <testcase name="VerifyMenu5" time="1.301" classname="TestngFiles.LoginVerification"/>
  <testcase name="VerifyMenu6" time="3.044" classname="TestngFiles.LoginVerification"/>
  <testcase name="VerifyMenu7" time="0.796" classname="TestngFiles.LoginVerification"/>
</testsuite> <!-- TestngFiles.LoginVerification -->
